<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="3" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-04T12:37:49Z" name="Default suite" finished-at="2019-06-04T12:46:59Z" duration-ms="550637">
    <groups>
    </groups>
    <test started-at="2019-06-04T12:37:49Z" name="Default test" finished-at="2019-06-04T12:46:59Z" duration-ms="550637">
      <class name="com.reports.testcases.TestCustomReportBuilders">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.reports.testcases.TestCustomReportBuilders@4c40b76e]" started-at="2019-06-04T12:37:49Z" name="setUp" finished-at="2019-06-04T12:37:59Z" duration-ms="10786" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCustomReportFor1Month_DepartmentWiseAllocation()[pri:1, instance:com.reports.testcases.TestCustomReportBuilders@4c40b76e]" started-at="2019-06-04T12:37:59Z" name="testCustomReportFor1Month_DepartmentWiseAllocation" finished-at="2019-06-04T12:38:04Z" duration-ms="4964" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomReportFor1Month_DepartmentWiseAllocation -->
        <test-method signature="testCustomReportFor4Month_DoctorRevenueDetailed()[pri:4, instance:com.reports.testcases.TestCustomReportBuilders@4c40b76e]" started-at="2019-06-04T12:38:04Z" name="testCustomReportFor4Month_DoctorRevenueDetailed" finished-at="2019-06-04T12:38:20Z" duration-ms="15380" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomReportFor4Month_DoctorRevenueDetailed -->
        <test-method signature="testCustomReportFor5Month_RadiologyTATReport()[pri:5, instance:com.reports.testcases.TestCustomReportBuilders@4c40b76e]" started-at="2019-06-04T12:38:20Z" name="testCustomReportFor5Month_RadiologyTATReport" finished-at="2019-06-04T12:40:30Z" duration-ms="130653" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[testCustomReportFor5Month_RadiologyTATReport got failed due to time out error. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: testCustomReportFor5Month_RadiologyTATReport got failed due to time out error. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at com.reports.testcases.TestCustomReportBuilders.failORPassStatment(TestCustomReportBuilders.java:62)
at com.reports.testcases.TestCustomReportBuilders.testCustomReportFor5Month_RadiologyTATReport(TestCustomReportBuilders.java:176)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomReportFor5Month_RadiologyTATReport -->
        <test-method signature="testCustomReportFor6Month_DepartmentwisePatientCount()[pri:6, instance:com.reports.testcases.TestCustomReportBuilders@4c40b76e]" started-at="2019-06-04T12:40:30Z" name="testCustomReportFor6Month_DepartmentwisePatientCount" finished-at="2019-06-04T12:42:30Z" duration-ms="120047" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[testCustomReportFor6Month_DepartmentwisePatientCount got failed due to time out error. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: testCustomReportFor6Month_DepartmentwisePatientCount got failed due to time out error. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at com.reports.testcases.TestCustomReportBuilders.failORPassStatment(TestCustomReportBuilders.java:62)
at com.reports.testcases.TestCustomReportBuilders.testCustomReportFor6Month_DepartmentwisePatientCount(TestCustomReportBuilders.java:197)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomReportFor6Month_DepartmentwisePatientCount -->
        <test-method signature="testCustomReportFor7Month_VisitStatusReportforHealthAuthority()[pri:7, instance:com.reports.testcases.TestCustomReportBuilders@4c40b76e]" started-at="2019-06-04T12:42:30Z" name="testCustomReportFor7Month_VisitStatusReportforHealthAuthority" finished-at="2019-06-04T12:44:47Z" duration-ms="137063" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[testCustomReportFor7Month_VisitStatusReportforHealthAuthority got failed due to time out error. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: testCustomReportFor7Month_VisitStatusReportforHealthAuthority got failed due to time out error. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at com.reports.testcases.TestCustomReportBuilders.failORPassStatment(TestCustomReportBuilders.java:62)
at com.reports.testcases.TestCustomReportBuilders.testCustomReportFor7Month_VisitStatusReportforHealthAuthority(TestCustomReportBuilders.java:212)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomReportFor7Month_VisitStatusReportforHealthAuthority -->
        <test-method signature="testCustomReportFor8Month_SubmissionRejectionRate()[pri:8, instance:com.reports.testcases.TestCustomReportBuilders@4c40b76e]" started-at="2019-06-04T12:44:47Z" name="testCustomReportFor8Month_SubmissionRejectionRate" finished-at="2019-06-04T12:46:50Z" duration-ms="122297" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[testCustomReportFor8Month_SubmissionRejectionRate got failed due to time out error. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: testCustomReportFor8Month_SubmissionRejectionRate got failed due to time out error. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at com.reports.testcases.TestCustomReportBuilders.failORPassStatment(TestCustomReportBuilders.java:62)
at com.reports.testcases.TestCustomReportBuilders.testCustomReportFor8Month_SubmissionRejectionRate(TestCustomReportBuilders.java:226)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomReportFor8Month_SubmissionRejectionRate -->
        <test-method signature="testCustomReportFor9Month_SponsorWiseClaimSubmissionList()[pri:9, instance:com.reports.testcases.TestCustomReportBuilders@4c40b76e]" started-at="2019-06-04T12:46:50Z" name="testCustomReportFor9Month_SponsorWiseClaimSubmissionList" finished-at="2019-06-04T12:46:59Z" duration-ms="9396" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomReportFor9Month_SponsorWiseClaimSubmissionList -->
      </class> <!-- com.reports.testcases.TestCustomReportBuilders -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
